spring:
  application:
    name: hello-server-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.38:8848
#    loadbalancer:
#      nacos:
#        enabled: true


#server:
#  port: 9100
